name: Continuous Integration

# This action works with pull requests and pushes
on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Install Node.js dependencies
        run: npm install --frozen-lockfile
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{ts,tsx,css,cjs,mjs}
          prettier_plugins: prettier-plugin-tailwindcss
